import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="max-w-7xl mx-auto">
          <Navbar></Navbar>
        {children}
        </div>
        </body>
    </html>
  );
}
